---
title: "Question 3 and 4"
output: html_document
---

## Question 3
## (a)

```{r}
#Question 3
# (a)
n<- 500
mu1<-mu2<-mu3<-0
sigma1<-sigma2<-sigma3<-1
z1<-rnorm(n,mu1,sigma1)
z2<-rnorm(n,mu2,sigma2)
z3<-rnorm(n,mu3,sigma3)

Y1<-1+z1
Y2<-5+2*z1+z2

#MAR
Y2_MAR_obs <- Y2[2*z1 +z3 >= 0]
mean(Y2_MAR_obs)

Y2_MAR_mis <- Y2[2*z1 +z3<0]
plot(density(Y2), lwd = 2, col = "blue", main = "MAR", ylim = c(0,0.3))
lines(density(Y2_MAR_obs), lwd = 2, col = "red")
legend(6, 0.3,legend = c("Complete data", "Observed data"),cex=0.8,
       col = c("blue", "red"), lty = c(1, 1), lwd = c(2, 2), bty = "n")

ind_MAR <- which(2*z1 +z3 >= 0) 
g1_MAR <- Y1[ind_MAR] 
g2_MAR <- Y1[-ind_MAR]
mean(g1_MAR)
mean(g2_MAR)
t.test(g1_MAR, g2_MAR, paired = FALSE, var.equal = FALSE)

```
## Question 3
## (b)

```{r}
#Question 3
# (b)
n<- 500
mu1<-mu2<-mu3<-0
sigma1<-sigma2<-sigma3<-1
z1<-rnorm(n,mu1,sigma1)
z2<-rnorm(n,mu2,sigma2)
z3<-rnorm(n,mu3,sigma3)

Y1<-1+z1
Y2<-5+2*z1+z2

Y2[2*z1 +z3<0]=NA

data<-data.frame(Y1=c(Y1), Y2=c(Y2))

fit <- lm(Y2 ~ Y1, data = data) 
summary(fit)
fit$coefficients

set.seed(111)
predicted_sri <- predict(fit, newdata = data) + rnorm(nrow(data), 0, sigma(fit))
Y2_sri <- ifelse(is.na(data$Y2), predicted_sri, data$Y2)

sd(data$Y2, na.rm = TRUE)
sd(Y2_sri)

plot(density(data$Y2[-which(is.na(data$Y2) == TRUE)]), lwd = 2, col = "blue", main = "Stochastic regression imputation", ylim = c(0,0.3))
lines(density(Y2_sri), lwd = 2, col = "red")
legend(6, 0.3,legend = c("Complete data", "Completed data(after imputation)"),cex=0.8,
       col = c("blue", "red"), lty = c(1, 1), lwd = c(2, 2), bty = "n")

```

## Question 3
## (c)

```{r}
#Question 3
# (c)
n<- 500
mu1<-mu2<-mu3<-0
sigma1<-sigma2<-sigma3<-1
z1<-rnorm(n,mu1,sigma1)
z2<-rnorm(n,mu2,sigma2)
z3<-rnorm(n,mu3,sigma3)

Y1<-1+z1
Y2<-5+2*z1+z2

#MNAR
Y2_MNAR_obs <- Y2[2*Y2-10+z3 >= 0]
Y2_MNAR_mis <- Y2[2*Y2-10+z3 < 0]

plot(density(Y2), lwd = 2, col = "blue", main = "MNAR", ylim = c(0,0.5))
lines(density(Y2_MNAR_obs), lwd = 2, col = "red")
legend(8, 0.5,legend = c("Complete data", "Observed data"),cex=0.8,
       col = c("blue", "red"), lty = c(1, 1), lwd = c(2, 2), bty = "n")
```

## Question 3
## (d)

```{r}
#Question 3
# (d)
n<- 500
mu1<-mu2<-mu3<-0
sigma1<-sigma2<-sigma3<-1
z1<-rnorm(n,mu1,sigma1)
z2<-rnorm(n,mu2,sigma2)
z3<-rnorm(n,mu3,sigma3)

Y1<-1+z1
Y2<-5+2*z1+z2

Y2[2*Y2-10+z3 < 0]=NA

data<-data.frame(Y1=c(Y1), Y2=c(Y2))

fit <- lm(Y2 ~ Y1, data = data) 
summary(fit)
fit$coefficients

set.seed(111)
predicted_sri <- predict(fit, newdata = data) + rnorm(nrow(data), 0, sigma(fit))
Y2_sri <- ifelse(is.na(data$Y2), predicted_sri, data$Y2)

sd(data$Y2, na.rm = TRUE)
sd(Y2_sri)

plot(density(data$Y2[-which(is.na(data$Y2) == TRUE)]), lwd = 2, col = "blue", main = "Stochastic regression imputation", ylim = c(0,0.5))
lines(density(Y2_sri), lwd = 2, col = "red")
legend(8, 0.5,legend = c("Complete data", "Completed data(after imputation)"),cex=0.8,
       col = c("blue", "red"), lty = c(1, 1), lwd = c(2, 2), bty = "n")

```


## Question 4
## (a)
```{r}

mean(databp$recovtime, na.rm = TRUE)
sd(databp$recovtime, na.rm = TRUE)

cor(databp$recovtime, databp$logdose, use = "complete")
cor(databp$recovtime, databp$bloodp, use = "complete")
```

## Question 4
## (b)
```{r}
mean(databp$recovtime, na.rm = TRUE)
re_mi <- ifelse(is.na(databp$recovtime), 19.27273, databp$recovtime)

mean(re_mi)
sd(re_mi)

cor(re_mi, databp$logdose)
cor(re_mi, databp$bloodp)
```

## Question 4
## (c)
```{r}
fit <- lm(recovtime ~ logdose+bloodp, data = databp) 
summary(fit)
fit$coefficients
predicted_ri <- predict(fit, newdata = databp)
re_ri <- ifelse(is.na(databp$recovtime), predicted_ri, databp$recovtime)
mean(re_ri)
sd(re_ri)

cor(re_ri, databp$logdose)
cor(re_ri, databp$bloodp)

```


## Question 4
## (d)
```{r}
fit <- lm(recovtime ~ logdose+bloodp, data = databp) 
summary(fit)
fit$coefficients


set.seed(111)
predicted_sri <- predict(fit, newdata = databp) + rnorm(nrow(databp), 0, sigma(fit))

re_sri <- ifelse(is.na(databp$recovtime), predicted_sri, databp$recovtime)
mean(re_sri)
sd(re_sri)

cor(re_sri, databp$logdose)
cor(re_sri, databp$bloodp)

```








